In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv(r"../data/processed/feature_engineered_data.csv")
df.head()

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday,Id,...,RollingMean_7,RollingMean_14,RollingMean_30,RollingStd_7,CompetitionAgeMonths,PromoDurationMonths,Month_sin,Month_cos,DayOfWeek_sin,DayOfWeek_cos
0,1,3,2013-02-06,6140,693,1,1,0,0,226264,...,5388.428571,5346.071429,5103.833333,1109.382990,53.966667,0.0,0.866025,0.5,0.433884,-0.900969
1,1,4,2013-02-07,5499,675,1,1,0,0,318919,...,5733.428571,5399.357143,5124.166667,851.378658,54.000000,0.0,0.866025,0.5,-0.433884,-0.900969
2,1,5,2013-02-08,5681,630,1,1,0,0,440864,...,5861.714286,5383.571429,5163.233333,707.864797,54.033333,0.0,0.866025,0.5,-0.974928,-0.222521
3,1,6,2013-02-09,5370,656,1,0,0,0,779012,...,6000.571429,5390.928571,5203.066667,512.408319,54.066667,0.0,0.866025,0.5,-0.781831,0.623490
4,1,1,2013-02-11,4409,599,1,0,0,0,179504,...,5963.000000,5403.428571,5215.500000,551.966786,54.133333,0.0,0.866025,0.5,0.781831,0.623490

In [25]:
df["Promo"].value_counts()

Promo
0    439500
1    357968
Name: count, dtype: int64

## KPIs

In [4]:
kpis = {
    "Total Sales": df["Sales"].sum(),
    "Average Daily Sales": df["Sales"].mean(),
    "Number of Stores": df["Store"].nunique(),
    "Average Promotion Sales": df[df["Promo"]==1]["Sales"].mean(),
    "Average Non-Promotion Sales": df[df["Promo"]==0]["Sales"].mean()
}

pd.DataFrame(kpis.items(), columns=["KPI","Value"])

                           KPI         Value
0                  Total Sales  5.565743e+09
1          Average Daily Sales  6.979269e+03
2             Number of Stores  1.115000e+03
3      Average Promotion Sales  8.244514e+03
4  Average Non-Promotion Sales  5.948740e+03

# Inventory Planning
| Forecast  | Recommendation          |
| --------- | ----------------------- |
| Very High | Increase inventory      |
| High      | Moderate stock increase |
| Medium    | Maintain normal stock   |
| Low       | Reduce inventory        |

## Promotion Strategy
Promotions consistently increase predicted sales. Stores with historically strong promotion response should be prioritized for future campaigns.

## Store-Level Recommendations

In [21]:
store_sales = (
    df.groupby("Store")["Sales"]
    .mean()
    .sort_values(ascending=False)
    .reset_index()
)
store_sales

      Store         Sales
0       817  21702.801887
1       262  20784.556793
2      1114  20730.636119
3       251  19167.852103
4       842  18646.274138
...     ...           ...
1110    841   2981.787263
1111    208   2938.460916
1112    198   2905.143243
1113    543   2790.941813
1114    307   2710.709459

[1115 rows x 2 columns]

 `High Performers`
- Maintain stock levels.
- Expand successful promotions.

`Average Performers`
- Optimize product assortment.
- Evaluate local competition.

`Low Performers`
- Review pricing.
- Assess store operations.
- Investigate demand patterns.

## Seasonal Planning

- **Peak Months**: January and March 
- **Lowest Months**: August, September, and October
- **Summer Slump**: Clear decline during summer months (July-October)
- **Recommendation**: Plan additional marketing and promotions during August-September to combat seasonal dip

## Staffing Recommendations
- High Forecast ➡️  More Cashiers ➡️ More Inventory Staff ➡️ Longer Store Hours
- Reduce Staffing ➡️ Reduce Operational Cost

## Risk Analysis

`Limitations`
- Forecasts rely on historical sales patterns.
- Unexpected events (pandemics, policy changes, extreme weather) are not modeled.
- Inventory shortages are not explicitly represented.
- Economic indicators and inflation were not included.

## Future Improvements

- Integrate weather data.
- Include local events and festivals.
- Add Google Trends data.
- Use deep learning models such as LSTM or Temporal Fusion Transformer.
- Deploy the model with FastAPI.
- Enable daily automatic retraining.